export const animateLeave = [
  {
    type: 'leave',
    name: 'fadeOut',
    id: 'fadeOut',
    ename: 'fadeOut',
    tips: '渐隐',
    frames: [
      { progress: 0, alpha: 1 },
      { progress: 0.5, alpha: 0.5 },
      { progress: 1, alpha: 0 },
    ],
  },
  {
    type: 'leave',
    name: 'fadeOutDown',
    id: 'fadeOutDown',
    ename: 'fadeOutDown',
    tips: '下渐隐',
    frames: [
      { progress: 0, alpha: 1, transform: { translateY: 0 } },
      { progress: 1, alpha: 0, transform: { translateY: 100 } },
    ],
  },
  {
    type: 'leave',
    name: 'fadeOutZoom',
    id: 'fadeOutZoom',
    ename: 'fadeOutZoom',
    tips: '放大渐隐',
    frames: [
      { progress: 0, alpha: 1, transform: { scaleX: 1, scaleY: 1 } },
      { progress: 1, alpha: 0, transform: { scaleX: 1.5, scaleY: 1.5 } },
    ],
  },
  {
    type: 'leave',
    name: 'fadeOutLeft',
    id: 'fadeOutLeft',
    ename: 'fadeOutLeft',
    tips: '左渐隐',
    frames: [
      { progress: 0, alpha: 1, transform: { translateX: 0 } },
      { progress: 1, alpha: 0, transform: { translateX: -100 } },
    ],
  },
  {
    type: 'leave',
    name: 'fadeOutRight',
    id: 'fadeOutRight',
    ename: 'fadeOutRight',
    tips: '右渐隐',
    frames: [
      { progress: 0, alpha: 1, transform: { translateX: 0 } },
      { progress: 1, alpha: 0, transform: { translateX: 100 } },
    ],
  },
  {
    type: 'leave',
    name: 'fadeOutTopLeft',
    id: 'fadeOutTopLeft',
    ename: 'fadeOutTopLeft',
    tips: '左上渐隐',
    frames: [
      { progress: 0, alpha: 1, transform: { translateX: 0, translateY: 0 } },
      { progress: 1, alpha: 0, transform: { translateX: -100, translateY: -100 } },
    ],
  },
  {
    type: 'leave',
    name: 'fadeOutTopRight',
    id: 'fadeOutTopRight',
    ename: 'fadeOutTopRight',
    tips: '右上渐隐',
    frames: [
      { progress: 0, alpha: 1, transform: { translateX: 0, translateY: 0 } },
      { progress: 1, alpha: 0, transform: { translateX: 100, translateY: -100 } },
    ],
  },
  {
    type: 'leave',
    name: 'fadeOutBottomRight',
    id: 'fadeOutBottomRight',
    ename: 'fadeOutBottomRight',
    tips: '右下渐隐',
    frames: [
      { progress: 0, alpha: 1, transform: { translateX: 0, translateY: 0 } },
      { progress: 1, alpha: 0, transform: { translateX: 100, translateY: 100 } },
    ],
  },
  {
    type: 'leave',
    name: 'backOutDown',
    id: 'backOutDown',
    ename: 'backOutDown',
    tips: '下后渐隐',
    frames: [
      { progress: 0, alpha: 1, transform: { scaleX: 1, scaleY: 1 } },
      { progress: 0.2, alpha: 0.7, transform: { translateY: 0, scaleX: 0.7, scaleY: 0.7 } },
      { progress: 1, alpha: 0.7, transform: { translateY: 700, scaleX: 0.7, scaleY: 0.7 } },
    ],
  },
  {
    type: 'leave',
    name: 'backOutLeft',
    id: 'backOutLeft',
    ename: 'backOutLeft',
    tips: '左后渐隐',
    frames: [
      { progress: 0, alpha: 1, transform: { scaleX: 1, scaleY: 1 } },
      { progress: 0.2, alpha: 0.7, transform: { translateY: 0, scaleX: 0.7, scaleY: 0.7 } },
      { progress: 1, alpha: 0.7, transform: { translateY: -2000, scaleX: 0.7, scaleY: 0.7 } },
    ],
  },
  {
    type: 'leave',
    name: 'backOutRight',
    id: 'backOutRight',
    ename: 'backOutRight',
    tips: '右后渐隐',
    frames: [
      { progress: 0, alpha: 1, transform: { scaleX: 1, scaleY: 1 } },
      { progress: 0.2, alpha: 0.7, transform: { translateY: 0, scaleX: 0.7, scaleY: 0.7 } },
      { progress: 1, alpha: 0, transform: { translateY: 2000, scaleX: 0.7, scaleY: 0.7 } },
    ],
  },
  {
    type: 'leave',
    name: 'backOutUp',
    id: 'backOutUp',
    ename: 'backOutUp',
    tips: '上后渐隐',
    frames: [
      { progress: 0, alpha: 1, transform: { scaleX: 1, scaleY: 1 } },
      { progress: 0.2, alpha: 0.7, transform: { translateY: 0, scaleX: 0.7, scaleY: 0.7 } },
      { progress: 1, alpha: 0, transform: { translateY: -700, scaleX: 0.7, scaleY: 0.7 } },
    ],
  },
  {
    type: 'leave',
    name: 'bounceOut',
    id: 'bounceOut',
    ename: 'bounceOut',
    tips: '弹走',
    frames: [
      { progress: 0, alpha: 1, transform: { scaleX: 1, scaleY: 1 } },
      { progress: 0.2, alpha: 1, transform: { scaleX: 0.9, scaleY: 0.9 } },
      { progress: 0.5, alpha: 1, transform: { scaleX: 1.1, scaleY: 1.1 } },
      { progress: 0.55, alpha: 1, transform: { scaleX: 1.1, scaleY: 1.1 } },
      { progress: 1, alpha: 0, transform: { scaleX: 0.3, scaleY: 0.3 } },
    ],
  },
  {
    type: 'leave',
    name: 'bounceOutDown',
    id: 'bounceOutDown',
    ename: 'bounceOutDown',
    tips: '下弹走',
    frames: [
      { progress: 0, alpha: 1, transform: { translateY: 0, scaleY: 1 } },
      { progress: 0.2, alpha: 1, transform: { translateY: 10, scaleY: 0.985 } },
      { progress: 0.4, alpha: 1, transform: { translateY: -20, scaleY: 0.9 } },
      { progress: 0.45, alpha: 1, transform: { translateY: -20, scaleY: 0.9 } },
      { progress: 1, alpha: 0, transform: { translateY: 2000, scaleY: 3 } },
    ],
  },
  {
    type: 'leave',
    name: 'bounceOutLeft',
    id: 'bounceOutLeft',
    ename: 'bounceOutLeft',
    tips: '左弹走',
    frames: [
      { progress: 0, alpha: 1, transform: { translateX: 0, scaleY: 1 } },
      { progress: 0.2, alpha: 1, transform: { translateX: 20, scaleY: 0.9 } },
      { progress: 1, alpha: 0, transform: { translateX: -2000, scaleY: 2 } },
    ],
  },
  {
    type: 'leave',
    name: 'bounceOutRight',
    id: 'bounceOutRight',
    ename: 'bounceOutRight',
    tips: '右弹走',
    frames: [
      { progress: 0, alpha: 1, transform: { translateX: 0, scaleY: 1 } },
      { progress: 0.2, alpha: 1, transform: { translateX: -20, scaleY: 0.9 } },
      { progress: 1, alpha: 0, transform: { translateX: 2000, scaleY: 2 } },
    ],
  },
  {
    type: 'leave',
    name: 'bounceOutUp',
    id: 'bounceOutUp',
    ename: 'bounceOutUp',
    tips: '上弹走',
    frames: [
      { progress: 0, alpha: 1, transform: { translateY: 0, scaleY: 1 } },
      { progress: 0.2, alpha: 1, transform: { translateY: -10, scaleY: 0.985 } },
      { progress: 0.4, alpha: 1, transform: { translateY: 20, scaleY: 0.9 } },
      { progress: 0.45, alpha: 1, transform: { translateY: 20, scaleY: 0.9 } },
      { progress: 1, alpha: 0, transform: { translateY: -2000, scaleY: 3 } },
    ],
  },
];
