import { AnimationItem } from './types';

export const animateEmphasize: AnimationItem[] = [
  {
    type: 'emphasize',
    name: 'zoom-in',
    ename: 'zoom-in',
    id: 'zoom-in',
    tips: '缩小',
    frames: [
      { progress: 0, transform: { scaleX: 1.2, scaleY: 1.2 } },
      { progress: 1, transform: { scaleX: 1, scaleY: 1 } },
    ],
  },
  {
    type: 'emphasize',
    name: 'zoom-out',
    ename: 'zoom-out',
    id: 'zoom-out',
    tips: '放大',
    frames: [
      { progress: 0, transform: { scaleX: 1, scaleY: 1 } },
      { progress: 1, transform: { scaleX: 1.2, scaleY: 1.2 } },
    ],
  },
  {
    type: 'emphasize',
    name: 'shake',
    ename: 'shake',
    id: 'shake',
    tips: '震动',
    frames: [
      { progress: 0, transform: { translateX: 0 } },
      { progress: 0.1, transform: { translateX: -10 } },
      { progress: 0.2, transform: { translateX: 10 } },
      { progress: 0.3, transform: { translateX: -10 } },
      { progress: 0.4, transform: { translateX: 10 } },
      { progress: 0.5, transform: { translateX: -10 } },
      { progress: 0.6, transform: { translateX: 10 } },
      { progress: 0.7, transform: { translateX: -10 } },
      { progress: 0.8, transform: { translateX: 10 } },
      { progress: 0.9, transform: { translateX: -10 } },
      { progress: 1, transform: { translateX: 0 } },
    ],
  },
  {
    type: 'emphasize',
    name: 'swing',
    ename: 'swing',
    id: 'swing',
    tips: '摇摆',
    frames: [
      { progress: 0, transform: { rotation: 0 } },
      { progress: 0.2, transform: { rotation: (Math.PI / 180) * 15 } },
      { progress: 0.4, transform: { rotation: (-Math.PI / 180) * 10 } },
      { progress: 0.6, transform: { rotation: (Math.PI / 180) * 5 } },
      { progress: 0.8, transform: { rotation: (-Math.PI / 180) * 5 } },
      { progress: 1, transform: { rotation: 0 } },
    ],
  },
  {
    type: 'emphasize',
    name: 'tada',
    ename: 'tada',
    id: 'tada',
    tips: '嘚瑟',
    frames: [
      { progress: 0, transform: { scaleX: 1, scaleY: 1, rotation: 0 } },
      { progress: 0.1, transform: { scaleX: 0.9, scaleY: 0.9, rotation: (-Math.PI / 180) * 3 } },
      { progress: 0.2, transform: { scaleX: 0.9, scaleY: 0.9, rotation: (-Math.PI / 180) * 3 } },
      { progress: 0.3, transform: { scaleX: 1.1, scaleY: 1.1, rotation: (Math.PI / 180) * 3 } },
      { progress: 0.4, transform: { scaleX: 1.1, scaleY: 1.1, rotation: (-Math.PI / 180) * 3 } },
      { progress: 0.5, transform: { scaleX: 1.1, scaleY: 1.1, rotation: (Math.PI / 180) * 3 } },
      { progress: 0.6, transform: { scaleX: 1.1, scaleY: 1.1, rotation: (-Math.PI / 180) * 3 } },
      { progress: 0.7, transform: { scaleX: 1.1, scaleY: 1.1, rotation: (Math.PI / 180) * 3 } },
      { progress: 0.8, transform: { scaleX: 1.1, scaleY: 1.1, rotation: (-Math.PI / 180) * 3 } },
      { progress: 0.9, transform: { scaleX: 1.1, scaleY: 1.1, rotation: (Math.PI / 180) * 3 } },
      { progress: 1, transform: { scaleX: 1, scaleY: 1, rotation: 0 } },
    ],
  },
  {
    type: 'emphasize',
    name: 'bounce',
    ename: 'bounce',
    id: 'bounce',
    tips: '跳动',
    frames: [
      { progress: 0, transform: { translateY: 0 } },
      { progress: 0.2, transform: { translateY: 0 } },
      { progress: 0.4, transform: { translateY: -30 } },
      { progress: 0.43, transform: { translateY: -30 } },
      { progress: 0.53, transform: { translateY: 0 } },
      { progress: 0.7, transform: { translateY: -15 } },
      { progress: 0.8, transform: { translateY: 0 } },
      { progress: 0.9, transform: { translateY: -4 } },
      { progress: 1, transform: { translateY: 0 } },
    ],
  },
  {
    type: 'emphasize',
    name: 'flash',
    ename: 'flash',
    id: 'flash',
    tips: '闪动',
    frames: [
      { progress: 0, alpha: 1 },
      { progress: 0.25, alpha: 0 },
      { progress: 0.5, alpha: 1 },
      { progress: 0.75, alpha: 0 },
      { progress: 1, alpha: 1 },
    ],
  },
  {
    type: 'emphasize',
    name: 'pulse',
    ename: 'pulse',
    id: 'pulse',
    tips: '呼吸',
    frames: [
      { progress: 0, transform: { scaleX: 1, scaleY: 1 } },
      { progress: 0.5, transform: { scaleX: 1.05, scaleY: 1.05 } },
      { progress: 1, transform: { scaleX: 1, scaleY: 1 } },
    ],
  },
  {
    type: 'emphasize',
    name: 'rubberBand',
    ename: 'rubberBand',
    id: 'rubberBand',
    tips: '弹性',
    frames: [
      { progress: 0, transform: { scaleX: 1, scaleY: 1 } },
      { progress: 0.3, transform: { scaleX: 1.25, scaleY: 0.75 } },
      { progress: 0.4, transform: { scaleX: 0.75, scaleY: 1.25 } },
      { progress: 0.5, transform: { scaleX: 1.15, scaleY: 0.85 } },
      { progress: 0.65, transform: { scaleX: 0.95, scaleY: 1.05 } },
      { progress: 0.75, transform: { scaleX: 1.05, scaleY: 0.95 } },
      { progress: 1, transform: { scaleX: 1, scaleY: 1 } },
    ],
  },
  {
    type: 'emphasize',
    name: 'shakeX',
    ename: 'shakeX',
    id: 'shakeX',
    tips: '水平震动',
    frames: [
      { progress: 0, transform: { translateX: 0 } },
      { progress: 0.1, transform: { translateX: -10 } },
      { progress: 0.2, transform: { translateX: 10 } },
      { progress: 0.3, transform: { translateX: -10 } },
      { progress: 0.4, transform: { translateX: 10 } },
      { progress: 0.5, transform: { translateX: -10 } },
      { progress: 0.6, transform: { translateX: 10 } },
      { progress: 0.7, transform: { translateX: -10 } },
      { progress: 0.8, transform: { translateX: 10 } },
      { progress: 0.9, transform: { translateX: -10 } },
      { progress: 1, transform: { translateX: 0 } },
    ],
  },
  {
    type: 'emphasize',
    name: 'shakeY',
    ename: 'shakeY',
    id: 'shakeY',
    tips: '垂直震动',
    frames: [
      { progress: 0, transform: { translateY: 0 } },
      { progress: 0.1, transform: { translateY: -10 } },
      { progress: 0.2, transform: { translateY: 10 } },
      { progress: 0.3, transform: { translateY: -10 } },
      { progress: 0.4, transform: { translateY: 10 } },
      { progress: 0.5, transform: { translateY: -10 } },
      { progress: 0.6, transform: { translateY: 10 } },
      { progress: 0.7, transform: { translateY: -10 } },
      { progress: 0.8, transform: { translateY: 10 } },
      { progress: 0.9, transform: { translateY: -10 } },
      { progress: 1, transform: { translateY: 0 } },
    ],
  },
  {
    type: 'emphasize',
    name: 'headShake',
    ename: 'headShake',
    id: 'headShake',
    tips: '头部震动',
    frames: [
      { progress: 0, transform: { translateX: 0, rotation: 0 } },
      { progress: 0.065, transform: { translateX: -6, rotation: (Math.PI / 180) * -9 } },
      { progress: 0.185, transform: { translateX: 5, rotation: (Math.PI / 180) * 7 } },
      { progress: 0.315, transform: { translateX: -3, rotation: (Math.PI / 180) * -5 } },
      { progress: 0.435, transform: { translateX: 2, rotation: (Math.PI / 180) * 3 } },
      { progress: 1, transform: { translateX: 0, rotation: 0 } },
    ],
  },
  {
    type: 'emphasize',
    name: 'heartBeat',
    ename: 'heartBeat',
    id: 'heartBeat',
    tips: '心跳',
    frames: [
      { progress: 0, transform: { scaleX: 1, scaleY: 1 } },
      { progress: 0.3, transform: { scaleX: 1.8, scaleY: 1.8 } },
      { progress: 0.6, transform: { scaleX: 0.5, scaleY: 0.5 } },
      { progress: 0.8, transform: { scaleX: 1.2, scaleY: 1.2 } },
      { progress: 1, transform: { scaleX: 1, scaleY: 1 } },
    ],
  },
  {
    type: 'emphasize',
    name: 'rotation1',
    ename: 'rotation1',
    id: 'rotation1',
    tips: '旋转',
    frames: new Array(2).fill(1).map((_d, i) => {
      return { progress: i / 1, transform: { rotation: i * Math.PI * 2 } };
    }),
  },
  {
    type: 'emphasize',
    name: 'jello',
    ename: 'jello',
    id: 'jello',
    tips: '拉扯',
    frames: [
      { progress: 0, transform: { skewX: 0, skewY: 0 } },
      { progress: 0.111, transform: { skewX: 0, skewY: 0 } },
      { progress: 0.222, transform: { skewX: (-12.5 * Math.PI) / 180, skewY: (-12.5 * Math.PI) / 180 } },
      { progress: 0.333, transform: { skewX: (6.25 * Math.PI) / 180, skewY: (6.25 * Math.PI) / 180 } },
      { progress: 0.444, transform: { skewX: (-3.125 * Math.PI) / 180, skewY: (-3.125 * Math.PI) / 180 } },
      { progress: 0.555, transform: { skewX: (1.5625 * Math.PI) / 180, skewY: (1.5625 * Math.PI) / 180 } },
      { progress: 0.666, transform: { skewX: (-0.78125 * Math.PI) / 180, skewY: (-0.78125 * Math.PI) / 180 } },
      { progress: 0.777, transform: { skewX: (0.390625 * Math.PI) / 180, skewY: (0.390625 * Math.PI) / 180 } },
      { progress: 0.888, transform: { skewX: (-0.1953125 * Math.PI) / 180, skewY: (-0.1953125 * Math.PI) / 180 } },
      { progress: 1, transform: { skewX: 0, skewY: 0 } },
    ],
  },
];
