import { AnimationItem } from './types';

export const animateEnter: AnimationItem[] = [
  {
    type: 'enter',
    name: 'fadeIn',
    id: 'fadeIn',
    ename: 'fadeIn',
    tips: '渐显',
    frames: [
      { progress: 0, alpha: 0 },
      { progress: 1, alpha: 1 },
    ],
  },
  {
    type: 'enter',
    name: 'fadeInDown',
    id: 'fadeInDown',
    ename: 'fadeInDown',
    tips: '上渐显',
    frames: [
      { progress: 0, alpha: 0, transform: { translateY: -100 } },
      { progress: 1, alpha: 1, transform: { translateY: 0 } },
    ],
  },
  {
    type: 'enter',
    name: 'fadeInUp',
    id: 'fadeInUp',
    ename: 'fadeInUp',
    tips: '下渐入',
    frames: [
      { progress: 0, alpha: 0, transform: { translateY: 100 } },
      { progress: 1, alpha: 1, transform: { translateY: 0 } },
    ],
  },
  {
    type: 'enter',
    name: 'fadeInLeft',
    id: 'fadeInLeft',
    ename: 'fadeInLeft',
    tips: '左渐显',
    frames: [
      { progress: 0, alpha: 0, transform: { translateX: -100 } },
      { progress: 1, alpha: 1, transform: { translateX: 0 } },
    ],
  },
  {
    type: 'enter',
    name: 'fadeInRight',
    id: 'fadeInRight',
    ename: 'fadeInRight',
    tips: '右渐入',
    frames: [
      { progress: 0, alpha: 0, transform: { translateX: 100 } },
      { progress: 1, alpha: 1, transform: { translateX: 0 } },
    ],
  },
  {
    type: 'enter',
    name: 'rotateIn',
    id: 'rotateIn',
    ename: 'rotateIn',
    tips: '滚入',
    frames: [
      { progress: 0, alpha: 0, transform: { rotation: 0 } },
      { progress: 1, alpha: 1, transform: { rotation: 6.283185307179586 } },
    ],
  },
  {
    type: 'enter',
    name: 'rollIn',
    id: 'rollIn',
    ename: 'rollIn',
    tips: '左滚入',
    frames: [
      { progress: 0, alpha: 0, transform: { rotation: 2.356194490192345, translateX: -100 } },
      { progress: 1, alpha: 1, transform: { rotation: 0, translateX: 0 } },
    ],
  },
  {
    type: 'enter',
    name: 'rotateInDownLeft',
    id: 'rotateInDownLeft',
    ename: 'rotateInDownLeft',
    tips: '左上滚入',
    frames: [
      { progress: 0, alpha: 0, transform: { rotation: -0.7853981633974483 } },
      { progress: 1, alpha: 1, transform: { rotation: 0 } },
    ],
  },
  {
    type: 'enter',
    name: 'rotateInDownRight',
    id: 'rotateInDownRight',
    ename: 'rotateInDownRight',
    tips: '右上滚入',
    frames: [
      { progress: 0, alpha: 0, transform: { rotation: 0.7853981633974483 } },
      { progress: 1, alpha: 1, transform: { rotation: 0 } },
    ],
  },
  {
    type: 'enter',
    name: 'bounceIn',
    id: 'bounceIn',
    ename: 'bounceIn',
    tips: '弹入',
    frames: [
      { progress: 0, alpha: 0, transform: { scaleX: 0.3, scaleY: 0.3 } },
      { progress: 0.2, alpha: 1, transform: { scaleX: 1.1, scaleY: 1.1 } },
      { progress: 0.4, alpha: 1, transform: { scaleX: 0.9, scaleY: 0.9 } },
      { progress: 0.6, alpha: 1, transform: { scaleX: 1.03, scaleY: 1.03 } },
      { progress: 0.8, alpha: 1, transform: { scaleX: 0.97, scaleY: 0.97 } },
      { progress: 1, alpha: 1, transform: { scaleX: 1, scaleY: 1 } },
    ],
  },
  {
    type: 'enter',
    name: 'bounceInDown',
    id: 'bounceInDown',
    ename: 'bounceInDown',
    tips: '上弹入',
    frames: [
      { progress: 0, alpha: 0, transform: { translateY: -1000 } },
      { progress: 0.6, alpha: 1, transform: { translateY: 25 } },
      { progress: 0.75, alpha: 1, transform: { translateY: -10 } },
      { progress: 0.9, alpha: 1, transform: { translateY: 5 } },
      { progress: 1, alpha: 1, transform: { translateY: 0 } },
    ],
  },
  {
    type: 'enter',
    name: 'bounceInLeft',
    id: 'bounceInLeft',
    ename: 'bounceInLeft',
    tips: '左弹入',
    frames: [
      { progress: 0, alpha: 0, transform: { translateX: -3000, scaleX: 3 } },
      { progress: 0.6, alpha: 1, transform: { translateX: 25, scaleX: 1 } },
      { progress: 0.75, alpha: 1, transform: { translateX: -10, scaleX: 0.98 } },
      { progress: 0.9, alpha: 1, transform: { translateX: 5, scaleX: 0.995 } },
      { progress: 1, alpha: 1, transform: { translateX: 0, scaleX: 1 } },
    ],
  },
  {
    type: 'enter',
    name: 'bounceInRight',
    id: 'bounceInRight',
    ename: 'bounceInRight',
    tips: '右弹入',
    frames: [
      { progress: 0, alpha: 0, transform: { translateX: 3000, scaleX: 3 } },
      { progress: 0.6, alpha: 1, transform: { translateX: -25, scaleX: 1 } },
      { progress: 0.75, alpha: 1, transform: { translateX: 10, scaleX: 0.98 } },
      { progress: 0.9, alpha: 1, transform: { translateX: -5, scaleX: 0.995 } },
      { progress: 1, alpha: 1, transform: { translateX: 0, scaleX: 1 } },
    ],
  },
  {
    type: 'enter',
    name: 'backInLeft',
    id: 'backInLeft',
    ename: 'backInLeft',
    tips: '左后弹入',
    frames: [
      { progress: 0, alpha: 0, transform: { translateX: -3000 } },
      { progress: 0.6, alpha: 1, transform: { translateX: 100 } },
      { progress: 0.75, alpha: 1, transform: { translateX: -80 } },
      { progress: 0.9, alpha: 1, transform: { translateX: 20 } },
      { progress: 1, alpha: 1, transform: { translateX: 0 } },
    ],
  },
  {
    type: 'enter',
    name: 'backInRight',
    id: 'backInRight',
    ename: 'backInRight',
    tips: '右后弹入',
    frames: [
      { progress: 0, alpha: 0, transform: { translateX: 3000 } },
      { progress: 0.6, alpha: 1, transform: { translateX: -100 } },
      { progress: 0.75, alpha: 1, transform: { translateX: 80 } },
      { progress: 0.9, alpha: 1, transform: { translateX: -20 } },
      { progress: 1, alpha: 1, transform: { translateX: 0 } },
    ],
  },
  {
    type: 'enter',
    name: 'backInDown',
    id: 'backInDown',
    ename: 'backInDown',
    tips: '向下放大',
    frames: [
      { progress: 0, alpha: 0.7, transform: { translateY: -1200, scaleX: 0.7, scaleY: 0.7 } },
      { progress: 0.8, alpha: 0.7, transform: { translateY: 0, scaleX: 0.7, scaleY: 0.7 } },
      { progress: 1, alpha: 1, transform: { translateY: 0, scaleX: 1, scaleY: 1 } },
    ],
  },
  {
    type: 'enter',
    name: 'backInUp',
    id: 'backInUp',
    ename: 'backInUp',
    tips: '向上放大',
    frames: [
      { progress: 0, alpha: 0.7, transform: { translateY: 1200, scaleX: 0.7, scaleY: 0.7 } },
      { progress: 0.8, alpha: 0.7, transform: { translateY: 0, scaleX: 0.7, scaleY: 0.7 } },
      { progress: 1, alpha: 1, transform: { translateY: 0, scaleX: 1, scaleY: 1 } },
    ],
  },
  {
    type: 'enter',
    name: 'zoomIn',
    id: 'zoomIn',
    ename: 'zoomIn',
    tips: '放大',
    frames: [
      { progress: 0, alpha: 0, transform: { scaleX: 0.3, scaleY: 0.3 } },
      { progress: 0.5, alpha: 0.5, transform: { scaleX: 0.5, scaleY: 0.5 } },
      { progress: 1, alpha: 1, transform: { scaleX: 1, scaleY: 1 } },
    ],
  },
  {
    type: 'enter',
    name: 'zoomRotateIn',
    id: 'zoomRotateIn',
    ename: 'zoomRotateIn',
    tips: '放大旋转',
    frames: [
      { progress: 0, alpha: 0, transform: { scaleX: 1, rotation: 0, scaleY: 1 } },
      { progress: 1, alpha: 1, transform: { scaleX: 1.3, rotation: Math.PI / 4, scaleY: 1.3 } },
    ],
  },
  {
    type: 'enter',
    name: 'jackInTheBox',
    id: 'jackInTheBox',
    ename: 'jackInTheBox',
    tips: '摆动放大',
    noText: true,
    frames: [
      { progress: 0, alpha: 0, transform: { rotation: 0.5235987755982988, scaleX: 0.1, scaleY: 0.1 } },
      { progress: 0.5, alpha: 0.5, transform: { rotation: -0.17453292519943295, scaleX: 0.5, scaleY: 0.5 } },
      { progress: 0.7, alpha: 0.7, transform: { rotation: 0.05235987755982989, scaleX: 0.7, scaleY: 0.7 } },
      { progress: 1, alpha: 1, transform: { rotation: 0, scaleX: 1, scaleY: 1 } },
    ],
  },
  {
    type: 'enter',
    name: 'lightSpeedInRight',
    id: 'lightSpeedInRight',
    ename: 'lightSpeedInRight',
    tips: '右摆入',
    noText: true,
    frames: [
      { progress: 0, alpha: 0, transform: { translateX: 100, skewX: -0.5235987755982988 } },
      { progress: 0.6, alpha: 1, transform: { skewX: 0.3490658503988659 } },
      { progress: 0.8, alpha: 1, transform: { skewX: -0.08726646259971647 } },
      { progress: 1, alpha: 1, transform: { translateX: 0 } },
    ],
  },
];
